server:
  port: 9090

spring:
     application:
      name: book-store
#    database
     datasource:
      url: jdbc:mysql://localhost:3306/library
      username: root
      password: Xaisingsoumang123
      driver-class-name: com.mysql.cj.jdbc.Driver
  #jpa
     jpa:
        properties:
         hibernate:
          order_insert: true
          jdbc:
            :batch_size: 50
          ddl-auto: update
        show-sql: true
        open-in-view: false


       #    logging:
#        level:
#          org:
#            hibernate:
#              SQL: DEBUG


  #    cache
     cache:
      type: redis
     redis:
      host: localhost
      port: 6379


      config:
        entryTtl: 60










